### PR TITLE
Use '§' character to indicate references to sections/paragraphs/whatever

### PR DESCRIPTION
**Pull request by Saser**
What the title says. Does not seem to produce any weird characters from what I have seen.

Compiled using Arch Linux's `texlive-most` distribution of LaTeX, and by running `make` twice from the root directory.

### CODE REVIEW

**Comment by lindskogen** [comment]
I like the idea! Maybe we could implement it by changing the ref style in some way instead to enforce it?

**Comment by Saser** [comment]
I created a basic command that is available in all files and can be used to refer to paragraphs. It is basically just an alias, but does what it is supposed to to. :stuck_out_tongue_winking_eye:

**Comment by lindskogen** [comment]
Nice! Will merge as soon as I know that I am able to :)

**Comment by Dr-Horv** [comment]
@lindskogen Soon?

**Pull request merged**
